name:  Github Pages

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Checkout Reports
      uses: actions/checkout@v2
      with:
        ref: 'reports'
        path: 'old-reports'

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install
      working-directory: ./ui

    - name: Build
      run: |
        npm run ng -- build --base-href /chacha-chart/
      working-directory: ./ui

    - name: Add Reports to static
      run: |
        cp old-reports/*.json dist/ui/reports/

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ui/dist/ui